name: CD-msvc-orders

on:
  workflow_run:
    workflows: ["CI-msvc-orders"]
    types: [completed]

jobs:
  docker:
    name: Build & Push Docker Image (Hybrid Mode)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Try to download artifact from CI
        id: download
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: msvc-orders-jar
          path: build/libs/

      - name: Set up JDK 21
        if: steps.download.outcome == 'failure'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle Wrapper
        if: steps.download.outcome == 'failure'
        run: chmod +x gradlew

      - name: Rebuild JAR locally (fallback)
        if: steps.download.outcome == 'failure'
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/orderdb
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 100juanU
          SPRING_PROFILES_ACTIVE: dev
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: guest
          RABBITMQ_PASS: guest
        run: ./gradlew clean build -x test --no-daemon

      - name: Verify JAR presence
        run: |
          echo "Verificando archivo JAR..."
          ls -l build/libs || exit 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/msvc-orders:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/msvc-orders:latest
